<a href="https://colab.research.google.com/github/abdulrah77/ineuron_assignments/blob/main/programming_assignment8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# 1. Write a Python Program to Add Two Matrices?
x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result=[[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(x)):
  for j in range(len(x[0])):
    result[i][j]=x[i][j]+y[i][j]
print(result)



[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


In [8]:

# 2. Write a Python Program to Multiply Two Matrices?
import numpy as np

x = [[2,7,3],
    [4 ,15,6],
    [7 ,8,9]]

y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result=[[0,0,0],[0,0,0],[0,0,0]]
result=np.dot(x,y)
print(result)

[[ 64  80  50]
 [134 167 103]
 [119 157 112]]


In [9]:

# 3. Write a Python Program to Transpose a Matrix?
x = [[2,7,3],
    [4 ,15,6],
    [7 ,8,9]]


result=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(x)):
  for j in range(len(x[0])):
    result[j][i]=x[i][j]
print(result)



[[2, 4, 7], [7, 15, 8], [3, 6, 9]]


In [27]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?

words = input("Enter the words to sort them alphabetically: ")
word_list = words.split()
sorted=[]
for word in range(len(word_list)): 
  word_list[word]=word_list[word].lower()
  # sorted.append(" ".join(word))
word_list.sort()
sorted=" ".join(word_list)
print(sorted)


Enter the words to sort them alphabetically: Write a Python Program to Remove Punctuation From a Strin
a a from program punctuation python remove strin to write


In [39]:
# 5. Write a Python Program to Remove Punctuation From a String?
import re

line = input("Enter a line to remove punctuations: ")
result = re.sub(r'[^\w\s]', '', line)
print(result)

Enter a line to remove punctuations: "cgc ,adj ytest 45 arre :;211
cgc adj ytest 45 arre 211
